# Generated by Django 5.2.7 on 2026-03-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('informacion', models.TextField()),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='modelos.muestra')),
            ],
        ),
        migrations.CreateModel(
            name='Micrografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micrografias', to='modelos.region')),
            ],
        ),
    ]
