version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # ✅ Ya NO depende de Redis local (usa el de la nube)
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}

  celery:
    build: .
    container_name: celery_worker
    command: celery -A albertidl worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    # ✅ Ya NO depende de Redis local
    environment:  
      - HF_TOKEN=${HF_TOKEN}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}