"""
Django settings for albertidl project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^qu$(t0qj4l#_(dbn)=u3o+q6xawnkhx6$$t9k@lah3+4o@*^y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://ec2-18-222-79-144.us-east-2.compute.amazonaws.com',
    'https://albertidl.vercel.app',
    'https://crucially-treacherous-madie.ngrok-free.dev',
    "https://shela-unmultiplying-chandler.ngrok-free.dev",
    "https://superdeclamatory-claris-prolongably.ngrok-free.dev",
    "http://localhost:4321",  # ✅ SIN slash final
    'http://localhost:8000',
    'alberti-tech.onrender.com', 
    
]

CORS_ALLOWED_ORIGINS  = [
    'https://ec2-18-222-79-144.us-east-2.compute.amazonaws.com',
    'https://albertidl.vercel.app',
    'https://crucially-treacherous-madie.ngrok-free.dev',
    "https://shela-unmultiplying-chandler.ngrok-free.dev",
    "https://superdeclamatory-claris-prolongably.ngrok-free.dev",
    "http://localhost:4321",  # 
    'http://localhost:8000',
    'alberti-tech.onrender.com', 
    
    
]

# settings.py
CSRF_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blogs',
    'corsheaders',
    'rest_framework',
    'metalografia',
    "rest_framework.authtoken",
    "member",
    'reports',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = False

ROOT_URLCONF = 'albertidl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'albertidl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


import os
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,           # recomendado
        ssl_require=True            # importante para Render
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Carpeta donde se guardarán los archivos subidos

# URL pública para acceder a los archivos subidos


# CSRF_COOKIE_SAMESITE = 'Lax'

# SESSION_COOKIE_SECURE = False

# CSRF_COOKIE_SECURE = False

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"




INSTALLED_APPS += ["django_celery_results"]

CELERY_RESULT_BACKEND = "django-db"

# CELERY_BROKER_URL = "redis://redis:6379/0"
# CELERY_BROKER_URL = "redis://localhost:6379/0"

import os

# Ruta absoluta a la carpeta donde están tus imágenes subidas
# MEDIA_ROOT = r"C:\Users\Alber\Documents\IA Metalurgia\Presentación\albertidl\back_copy"
# MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "albertifranco97@gmail.com"
EMAIL_HOST_PASSWORD = "yfaj cwbu zsqd zazl"


import os

# ====================== CELERY + REDIS ======================
REDIS_URL = os.getenv(
    'REDIS_URL',
    'redis://default:mtGKWJ8P9Gp94SmCM29Nf4SjKjQALMe6@redis-15093.c9.us-east-1-4.ec2.cloud.redislabs.com:15093/0'
)
CELERY_BROKER_URL = REDIS_URL
# CELERY_RESULT_BACKEND = REDIS_URL   # Recomendado usar Redis también para resultados

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Opcional pero recomendado para Celery en la nube
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True