# Generated by Django 5.2.7 on 2026-03-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Micrografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='micrografias/')),
            ],
        ),
        migrations.CreateModel(
            name='Micrografia_mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='micrografias_mask/')),
                ('micrografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micrografias_mask', to='metalografia.micrografia')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('informacion', models.TextField()),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='muestras/')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='metalografia.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='regiones/')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='metalografia.muestra')),
            ],
        ),
        migrations.AddField(
            model_name='micrografia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micrografias', to='metalografia.region'),
        ),
    ]
