# Generated by Django 5.2.7 on 2026-03-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('has_model', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='muestra',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='metalografia.material'),
        ),
    ]
