# Generated by Django 5.2.7 on 2026-03-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0002_material_alter_muestra_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='metalografia.categoria'),
        ),
    ]
