# Generated by Django 5.2.7 on 2026-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0003_alter_muestra_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrografia_mask',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='micrografia_mask',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='micrografias_mask/'),
        ),
    ]
