# Generated by Django 5.2.7 on 2026-03-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0004_micrografia_mask_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrografia_mask',
            name='micrografia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='micrografias_mask', to='metalografia.micrografia'),
        ),
    ]
