# Generated by Django 5.2.7 on 2026-03-14 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0005_alter_micrografia_mask_micrografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_size', models.FloatField()),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='metalografia.region')),
            ],
        ),
        migrations.CreateModel(
            name='MicrographyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_size', models.FloatField()),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grain', to='metalografia.grainsize')),
            ],
        ),
    ]
