# Generated by Django 5.2.7 on 2026-03-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0006_grainsize_micrographymeasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrographymeasure',
            name='region',
        ),
        migrations.AddField(
            model_name='micrographymeasure',
            name='micrografia',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grain', to='metalografia.micrografia'),
            preserve_default=False,
        ),
    ]
