# Generated by Django 5.2.7 on 2026-03-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0007_remove_micrographymeasure_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrographymeasure',
            name='mean_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
