# Generated by Django 5.2.7 on 2026-03-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0008_alter_micrographymeasure_mean_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrografia_mask',
            name='px_to_um',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
