# Generated by Django 5.2.7 on 2026-03-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0009_micrografia_mask_px_to_um'),
    ]

    operations = [
        migrations.RenameField(
            model_name='micrografia_mask',
            old_name='px_to_um',
            new_name='px_by_um',
        ),
    ]
