# Generated by Django 5.2.7 on 2026-03-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0010_rename_px_to_um_micrografia_mask_px_by_um'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrografia_mask',
            name='px_by_um',
        ),
        migrations.AddField(
            model_name='micrografia',
            name='px_by_um',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
