# Generated by Django 5.2.7 on 2026-03-15 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0011_remove_micrografia_mask_px_by_um_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainsize',
            name='mean_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grainsize',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region_measure', to='metalografia.region'),
        ),
        migrations.AlterField(
            model_name='micrographymeasure',
            name='micrografia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measure_micro', to='metalografia.micrografia'),
        ),
    ]
