# Generated by Django 5.2.7 on 2026-03-17 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('metalografia', '0012_alter_grainsize_mean_size_alter_grainsize_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_muestras', to='member.company'),
        ),
    ]
