# Generated by Django 5.2.7 on 2026-03-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0013_muestra_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestra', to='metalografia.muestra'),
        ),
    ]
