# Generated by Django 5.2.7 on 2026-03-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0014_alter_region_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
