# Generated by Django 5.2.7 on 2026-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0015_alter_muestra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrografia',
            name='imagen',
            field=models.ImageField(upload_to='media/micrografias/'),
        ),
        migrations.AlterField(
            model_name='micrografia_mask',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/micrografias_mask/'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='imagen',
            field=models.ImageField(upload_to='media/muestras/'),
        ),
        migrations.AlterField(
            model_name='region',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/regiones/'),
        ),
    ]
