# Generated by Django 5.2.7 on 2026-03-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0016_alter_micrografia_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='micrografia',
            old_name='px_by_um',
            new_name='um_by_px',
        ),
    ]
