# Generated by Django 5.2.7 on 2026-03-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0017_rename_px_by_um_micrografia_um_by_px'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='micrografia',
            constraint=models.UniqueConstraint(fields=('region', 'nombre'), name='unique_micrografia_por_region'),
        ),
    ]
