# Generated by Django 5.2.7 on 2026-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0018_micrografia_unique_micrografia_por_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrografia_mask',
            name='puntaje',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='micrografia_mask',
            name='valid_image',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
