# Generated by Django 5.2.7 on 2026-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0019_micrografia_mask_puntaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrografia_mask',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='micrografia_mask',
            name='valid_image',
        ),
        migrations.AddField(
            model_name='micrographymeasure',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
