# Generated by Django 5.0.5 on 2026-03-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0020_remove_micrografia_mask_puntaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrografia',
            name='imagen',
            field=models.ImageField(upload_to='micrografias/'),
        ),
        migrations.AlterField(
            model_name='micrografia_mask',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='micrografias_mask/'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='imagen',
            field=models.ImageField(upload_to='muestras/'),
        ),
        migrations.AlterField(
            model_name='region',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='regiones/'),
        ),
    ]
