# Generated by Django 5.0.5 on 2026-03-31 00:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0021_alter_micrografia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
