# Generated by Django 5.0.5 on 2026-03-31 16:27

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0022_alter_muestra_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrografia',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='micrografia_mask',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='micrografia_mask',
            name='micrografia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micrografias_mask', to='metalografia.micrografia'),
        ),
        migrations.AlterField(
            model_name='region',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MultiMicrografia_mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('micrografia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metalografia.micrografia')),
            ],
        ),
    ]
