# Generated by Django 5.0.5 on 2026-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0023_alter_micrografia_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrographymeasure',
            name='distribution',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
