# Generated by Django 5.0.5 on 2026-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0024_micrographymeasure_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micrographymeasure',
            name='distribution',
        ),
        migrations.AddField(
            model_name='micrographymeasure',
            name='distribution_quantiles',
            field=models.JSONField(blank=True, default=dict, help_text='10 deciles de los tamaños de grano individuales en píxeles', null=True),
        ),
    ]
