# Generated by Django 5.0.5 on 2026-04-12 02:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0025_remove_micrographymeasure_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrographymeasure',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
