# Generated by Django 5.0.5 on 2026-04-12 20:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0026_micrographymeasure_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrografia_mask',
            name='imagen_multiclass',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='MultiMicrografia_mask',
        ),
    ]
