# Generated by Django 5.0.5 on 2026-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalografia', '0027_micrografia_mask_imagen_multiclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrografia',
            name='polygon_file',
            field=models.FileField(blank=True, null=True, upload_to='polygons/%Y/%m/%d/', verbose_name='Archivo de Polígonos'),
        ),
    ]
