# Generated by Django 5.2.7 on 2026-01-24 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('read_time', models.CharField(max_length=20)),
                ('image', models.URLField()),
                ('is_featured', models.BooleanField(default=False)),
                ('youtube_id', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.author')),
            ],
        ),
    ]
