# Generated by Django 5.2.7 on 2026-03-19 00:53

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_alter_company_image'),
        ('metalografia', '0016_alter_micrografia_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='media/reports/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(default=reports.models.generate_code, max_length=8, unique=True)),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_muestra', to='metalografia.muestra')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_reports', to='member.member')),
            ],
        ),
    ]
