# Generated by Django 5.2.7 on 2026-03-19 00:53

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpdf',
            name='value',
            field=models.CharField(blank=True, default=reports.models.generate_code, max_length=8, null=True),
        ),
    ]
