# Generated by Django 5.2.7 on 2026-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportpdf_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpdf',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
