# Generated by Django 5.2.7 on 2026-03-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportpdf_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpdf',
            name='mail_sent',
        ),
    ]
