# Generated by Django 5.0.5 on 2026-03-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_reportpdf_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpdf',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reports/'),
        ),
    ]
