# Generated by Django 5.0.5 on 2026-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportpdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpdf',
            name='has_mask',
            field=models.BooleanField(default=False),
        ),
    ]
